<?php

namespace GameBundle\Repository;

/**
 * belongsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class belongsRepository extends \Doctrine\ORM\EntityRepository
{
}
