<?php

namespace GameBundle\Repository;

/**
 * enemyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class enemyRepository extends \Doctrine\ORM\EntityRepository
{
}
