user_user:
    resource: "@UserBundle/Controller/userController.php"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation

login:
    path: /login
    defaults: { _controller: UserBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout