<?php

namespace UserBundle\Repository;

/**
 * CHARACRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CHARACRepository extends \Doctrine\ORM\EntityRepository
{
}
