<?php

namespace UserBundle\Repository;

/**
 * CLASSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CLASSRepository extends \Doctrine\ORM\EntityRepository
{
}
