<?php

namespace UserBundle\Repository;

/**
 * ENEMYRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ENEMYRepository extends \Doctrine\ORM\EntityRepository
{
}
