<?php

namespace UserBundle\Repository;

/**
 * INVENTORYRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class INVENTORYRepository extends \Doctrine\ORM\EntityRepository
{
}
