<?php

namespace UserBundle\Repository;

/**
 * OBJECTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OBJECTRepository extends \Doctrine\ORM\EntityRepository
{
}
