<?php

namespace UserBundle\Repository;

/**
 * RACERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RACERepository extends \Doctrine\ORM\EntityRepository
{
}
