<?php

namespace UserBundle\Repository;

/**
 * ROOMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ROOMRepository extends \Doctrine\ORM\EntityRepository
{
}
