<?php

namespace UserBundle\Repository;

/**
 * STORYRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class STORYRepository extends \Doctrine\ORM\EntityRepository
{
}
